import React, { useState, useEffect } from "react";

export function EditorialBoardsTable({ items, onEdit, onDelete }) {
  if (items.length === 0) return <div className="card p-12 text-center bg-slate-50 border-2 border-dashed border-slate-200 text-slate-400">No Editorial Board Entries Found</div>;
  return (
    <div className="overflow-x-auto card border-slate-200"><table className="w-full text-left text-sm text-slate-600"><thead className="bg-slate-50 text-xs uppercase text-slate-500 border-b border-slate-200"><tr><th className="px-6 py-4 font-semibold">Board Name</th><th className="px-6 py-4 font-semibold">Role</th><th className="px-6 py-4 font-semibold">Year</th><th className="px-6 py-4 font-semibold">Level</th><th className="px-6 py-4 font-semibold text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100 italic-last-row">{items.map((item) => (
      <tr key={item._id} className="hover:bg-slate-50 transition-colors"><td className="px-6 py-4 font-bold text-slate-900 leading-tight">{item.boardName}</td><td className="px-6 py-4 text-indigo-600 font-semibold">{item.role}</td><td className="px-6 py-4 text-slate-500 font-medium">{item.academicYear}</td><td className="px-6 py-4"><span className="px-2 py-0.5 bg-slate-100 text-slate-600 rounded text-[10px] font-bold uppercase tracking-wider">{item.level}</span></td><td className="px-6 py-4 text-right flex justify-end gap-2"><button onClick={() => onEdit(item)} className="p-2 text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg></button><button onClick={() => onDelete(item)} className="p-2 text-red-500 hover:bg-red-50 rounded-lg transition-colors"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg></button></td></tr>))}</tbody></table></div>
  );
}

export function EditorialBoardFormModal({ isOpen, onClose, onSubmit, initialData }) {
  const [formData, setFormData] = useState({ academicYear: "", boardName: "", role: "Reviewer", level: "National", responsibilities: "" });
  const [loading, setLoading] = useState(false);
  useEffect(() => { if (isOpen && initialData) setFormData(initialData); else if (isOpen && !initialData) setFormData({ academicYear: "", boardName: "", role: "Reviewer", level: "National", responsibilities: "" }); }, [isOpen, initialData]);
  if (!isOpen) return null;
  const hC = (e) => setFormData(p => ({ ...p, [e.target.name]: e.target.value }));
  const hS = async (e) => { e.preventDefault(); setLoading(true); try { await onSubmit(formData); onClose(); } catch (err) { alert(err.message); } finally { setLoading(false); } };
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 overflow-y-auto"><div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm" onClick={onClose} /><div className="relative w-full max-w-2xl bg-white rounded-3xl shadow-2xl p-8 max-h-[90vh] overflow-y-auto"><h2 className="text-2xl font-bold mb-6">Editorial Board Entry</h2><form onSubmit={hS} className="space-y-4 shadow-none"><input required name="boardName" value={formData.boardName} onChange={hC} className="input" placeholder="Board / Journal Name" /><div className="grid grid-cols-2 gap-4"><select name="role" value={formData.role} onChange={hC} className="input"><option value="Editor-in-Chief">Editor-in-Chief</option><option value="Associate Editor">Associate Editor</option><option value="Reviewer">Reviewer</option><option value="Editorial Board Member">Editorial Board Member</option></select><select name="level" value={formData.level} onChange={hC} className="input"><option value="Local">Local</option><option value="National">National</option><option value="International">International</option></select></div><input required name="academicYear" value={formData.academicYear} onChange={hC} className="input" placeholder="Academic Year" /><div className="flex justify-end gap-2 pt-4"><button type="button" onClick={onClose} className="btn-secondary">Cancel</button><button type="submit" disabled={loading} className="btn-primary">Save Entry</button></div></form></div></div>
  );
}
